services:
  stratos-db:
    image: docker.io/postgres:latest
    container_name: ${CONTAINER_NAME_DB}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d stratos"]
      interval: 3s
      timeout: 3s
      retries: 4
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./server/src/config/init.sql:/docker-entrypoint-initdb.d/init.sql

  stratos:
    container_name: ${CONTAINER_NAME}
    image: localhost/stratos:dev
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - ${SERVER_PORT}:3000
    depends_on:
      stratos-db:
        condition: service_healthy
      stratos-ai:
        condition: service_started
    environment:
      - AI_URL=http://stratos-ai:5001
    volumes:
      - ./server/logs:/app/logs
      - uploads:/app/uploads
      - outputs:/app/outputs
  
  stratos-ai:
    container_name: ${CONTAINER_NAME_AI}
    image: localhost/stratos-ai:dev
    extends:
      file: ai/hwaccel.yml
      service: ${HWACCEL}
    build:
      context: ai
      dockerfile: Dockerfile.${HWACCEL}
    ports:
      - "5001:5001"
    volumes:
      - uploads:/app/uploads
      - outputs:/app/outputs
    restart: always

volumes:
  postgres:
    name: stratos-postgres
  uploads:
    name: stratos-uploads
  outputs:
    name: stratos-outputs

networks:
  default:
    name: stratos-network