services:
  db:
    image: postgres:latest
    container_name: stratos-db
    healthcheck: #this causes server to take a little longer to load
      test: ["CMD-SHELL", "pg_isready -U user -d stratos"]
      interval: 3s
      timeout: 3s
      retries: 3
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass 
      POSTGRES_DB: stratos
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./src/config/init.sql:/docker-entrypoint-initdb.d/init.sql

  backend:
    build:
      context: . 
      dockerfile: Dockerfile
    container_name: stratos-backend
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy
      ai_service:
        condition: service_started
    environment:
      - AI_SERVICE_URL=http://ai_service:5001
    volumes:
      - ./logs:/app/logs 
      - ./uploads:/app/uploads

  ai_service:
    build:
      context: ../ai_service
      dockerfile: Dockerfile
    container_name: stratos-ai-service
    ports:
      - "5001:5001"
    volumes:
      - ../ai_service/uploads:/app/ai/uploads
      - ../ai_service/models:/app/ai/models
    restart: always

volumes:
  postgres_data: