services:
  db:
    image: postgres:latest
    container_name: stratos-db
    healthcheck: #this causes server to take a little longer to load
      test: ["CMD-SHELL", "pg_isready -U user -d stratos"]
      interval: 3s
      timeout: 3s
      retries: 3
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass 
      POSTGRES_DB: stratos
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./src/config/init.sql:/docker-entrypoint-initdb.d/init.sql

  backend:
    build:
      context: . 
      dockerfile: Dockerfile
    ports:
      - "4000:3000"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./logs:/app/logs 
      - ./uploads:/app/uploads

volumes:
  postgres_data:
