services:
  database:
    image: docker.io/postgres:latest
    container_name: stratos-database
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d stratos"]
      interval: 3s
      timeout: 3s
      retries: 4
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass 
      POSTGRES_DB: stratos
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./src/config/init.sql:/docker-entrypoint-initdb.d/init.sql

  backend:
    container_name: stratos-server
    image: localhost/stratos:dev
    build:
      context: . 
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      database:
        condition: service_healthy
    volumes:
      - ./logs:/app/logs 
      - ./uploads:/app/uploads
    
volumes:
  postgres_data:
