services:
  db:
    image: postgres:latest
    container_name: stratos-db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass 
      POSTGRES_DB: stratos
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: . 
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - db

volumes:
  postgres_data:
