name: Build CI
on:
  push:
    branches:
      - master 
  pull_request:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: self-hosted
    strategy:
      matrix:
        directory: [server, web]
    steps:
    - uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Setup Bun
      uses: oven-sh/setup-bun@v2

    - name: Install Dependencies
      run: bun install
      working-directory: ${{ matrix.directory }}
        
    - name: Run Tests
      run: bun test
      working-directory: ${{ matrix.directory }}

    - name: Run Linter
      run: bun run lint
      working-directory: ${{ matrix.directory }}

    - name: Build Project
      run: bun run build
      working-directory: ${{ matrix.directory }}
        
    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build-artifact-${{ matrix.directory }}
        path: ${{ matrix.directory }}/build

  format:
    if: github.event_name == 'push'
    runs-on: self-hosted
    needs: build

    steps:
    - uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Setup Bun
      uses: oven-sh/setup-bun@v1
        
    - name: Install Dependencies
      run: |
        (cd server && bun install)
        (cd web && bun install)
    
    - name: Run Formatter
      run: |
        (cd server && bun run format)
        (cd web && bun run format)

    - name: Push Changes
      run: |
        git diff --quiet && echo "No formatting changes." && exit 0
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git commit -am "style: auto-format code"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
